### ISSUE TITLE
User Story - Social Media Integration

### ISSUE THREAD

**Issue by sd-powell** [sd-powell/portfolio_project_1#3]
**User Story**

As a visitor or fan, I want to see links to the DJ’s social media profiles so I can follow and engage with the DJ on different platforms.

**Acceptance Criteria:**

- [x] Each page on the site displays social media icons that are in a prominent position.
- [x] Each link displays an icon making the social media platform easily recognisable.
- [x] Each link opens the social media page in a new window.

**Tasks:**

- [x] Add social media buttons to the nav bar section of the homepage.
- [x] Include Instagram, Facebook, X, YouTube, Twitch, Mixcloud, Soundcloud.
- [x] Feature font awesome icons for each social media platform.
