### ISSUE TITLE
User Story - Event Information

### ISSUE THREAD

**Issue by sd-powell** [sd-powell/portfolio_project_1#4]
**User Story**

As a fan or event organiser, I want to view upcoming events and DJ availability so that I can plan for events or book for private gatherings.

**Acceptance Criteria:**

- [ ] On the homepage there is an upcoming events section.
- [ ] Each event lists the date, location and time of the event.
- [ ] When clicked, each listing links to the venue of the event.

**Tasks:**

- [ ] Add an events section to the homepage with upcoming events.
- [ ] Make the section scrollable to hold past and future events.
- [ ] Link each event to the venue's website in an external website.
